openapi: 3.0.3
info:
  title: AAS Nameplate Generator - OpenAPI 3.0
  description: |-
    The Digital Nameplate as product identification shall represent the Digital Product Passport (DPP) and contains the essential product identification in digital form. This information can be read using smartphones and tablets without the need for an internet connection. The technological basis was defined in the DIN SPEC 91406 and its international further development IEC 61406 as well as the VDE V 0170-100 as pre-standard for the international IEC 63365 standard.

    It is a project created in the scope of the course "Software Engineering" at Baden-Wuerttemberg Cooperative State University (DHBW) Stuttgart.


    
    Some useful links:
    - [The Nameplate Generator repository](https://github.com/TTRSF/TINF22F-Team2-Nameplate-Generator)
    - [The source API definition for the Nameplate Generator](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
  termsOfService: http://swagger.io/terms/
  contact:
    name:  the Developers
    email: AASNameplateGenerator@gmail.com
  license:
    name: Apache 2.0

    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
servers:
  - url: localhost
tags:
  - name: Nameplate
    description: Generate your Nameplate
paths:
  /Nameplate/GenerateByReference:
    get:
      tags:
        - Nameplate
      summary: Generating your Nameplate by a reference to a product
      description: Returns a SVG that was generated by a reference to an actual product
      operationId: GenerateByReference
      parameters:
        - name: URL
          in: query
          description: URL to the Product 
          required: false
          explode: true
          schema:
            type: string
            default: available
            enum:
              - available
              - pending
              - sold
      responses:
        '200':
          description: successful operation
          content:
            text/html:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GenerateByData'          

        '400':
          description: Invalid status value

  /Nameplate/GenerateByData:
    post:
      tags:
        - Nameplate
      summary: Generating your Nameplate by your own data.
      description: Returns a SVG that was generated by your own data.
      operationId: GenerateByData
      parameters:
        - name: idShort
          in: query
          description: short ID of the product
          required: false
          explode: true
          schema:
            type: string
            default: available
            enum:
              - available
              - pending
              - sold
        - name: id
          in: query
          description: ID of the product
          required: false
          explode: true
          schema:
            type: string
            default: available
            enum:
              - available
              - pending
              - sold
        - name: num
          in: query
          description: num of Nameplate
          required: false
          explode: true
          schema:
            type: integer
            default: available
            enum:
              - available
              - pending
              - sold
        - name: Nameplate
          in: query
          description: Nameplate data
          required: false
          explode: true
          schema:
            type: object
            properties:
              idShort:
                type: string
              id:
               type: string
              semanticId: 
                type: string
              ManufacturerName:
                type: string
              ManufacturerProductFamily:
                type: string
              ManufacturerProductDesignation:
                type: string
              OrderCode:
                type: string
              Address:
                type: object
                properties:
                  Department:
                    type: string
                  Street: 
                    type: string
                  ZipCode:
                    type: string
                  City_Town:
                    type: string
                  State_Country:
                    type: string
                  VATNumber:
                    type: string
                  AddressOfAdditionalLink:
                    type: string
                  Phone:
                    type: object
                    properties:
                      TelephoneNumber:
                        type: string
                  
                  
      responses:
        '200':
          description: successful operation
          content:
            text/html:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GenerateByData'          
components:
  schemas:
    GenerateByData:
      type: object
      properties:
        idShort:
          type: string
          example: "Norgren_B84G_4GK_AP3_RME"
        id:
          type: string
          example: "https://www.norgren.com/ids/aas/4DEF2ED7"
        num:
          type: integer
          example: 0
        nameplate:
          type: object
          properties:
            idShort:
              type: string
              example: "Nameplate"
            id:
              type: string
              example: "www.example.com/ids/sm/7002_0231_5022_3368"
            semanticId:
              type: string
              example: "https://admin-shell.io/zvei/nameplate/1/0/Nameplate"
            ManufacturerName:
              type: string
              example: "Norgren GmbH"
            ManufacturerProductFamily:
              type: string
              example: "Excelon Plus"
            ManufacturerProductDesignation:
              type: string
              example: "Filterregler, G3/8, 40µm, 0,3-10bar, automatische Entleerung"
            OrderCode:
              type: string
              example: "B84G-4GK-AP3-RME"
            Address:
              type: object
              properties:
                Department: 
                  type: string
                  example: "Kontakt zu Norgren"
                Street:
                  type: string
                  example: "Bruckstr. 93"
                ZipCode:
                  type: string
                  example: "46519"
                City_Town:
                  type: string
                  example: "Alpen"
                State_Country:
                  type: string
                  example: "Nordrhein Westfalen"
                VATNumber: 
                  type: string
                  example: "DE191308280"
                AddressOfAdditionalLink:
                  type: string
                  example: "www.norgren.com"
                Phone: 
                  type: object
                  properties:
                    TelephoneNumber:
                      type: string
                      example: "+49 (0) 2802 49 0"
            
        
    
